# Generated by Django 4.0.4 on 2022-05-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Halalan2022', '0002_user_birthday_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(default='', max_length=300),
        ),
    ]
